### ISSUE TITLE
A general problem in running the package

### ISSUE THREAD

**Issue by farshadniazi** [seanjohnite/PTENpred#1]
After making the virtualenv and successfully installing all dependencies I still get this error when I run the command  "" ./classifyMutation.py L70P "" :

Traceback (most recent call last):
  File "./classifyMutation.py", line 166, in <module>
    main()
  File "./classifyMutation.py", line 127, in main
    wwwString, num_cats, prob[probs]
  File "./classifyMutation.py", line 40, in load_pred_pack
    return joblib.load(filename)
  File "/home/farshad/Projects/CCF/PTENpredenv/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 425, in load
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    **import**(module)
ImportError: No module named classification

I can not specify what is wrong!

**Comment by seanjohnite** [comment]
Hi Farshad,

I think I've got a working solution here--there are some command line arguments that will change the way the program runs. Putting in `-mk True` will rebuild the prediction package and resave it. I have found that sometimes different computers will save python objects in different ways, and this sometimes clears up the differences. Try

`./classifyMutation.py -mk True L70P`
